baseURL: https://alm-research.com #replaced during the build
languageCode: en-us
title: Alexander Mykolaichuk - Personal Blog
theme: alm-minimal
disableKinds: ["taxonomy", "taxonomyTerm"]

Author:
  name: Alexander Mykolaichuk
  about: Software Engineer / Distributed Systems / Cloud Native

Params:
  githubEditPath: https://github.com/almmiko/alm-blog/edit/main/content/

Social:
  twitter: https://twitter.com/almmiko
  github: https://github.com/almmiko
  linkedin: https://www.linkedin.com/in/alexander-mykolaichuk

Markup:
  highlight:
    noClasses: false

